version: "2"
services:
  frp-server:
    image: hyperapp/frp
    ports:
     - "7000-7800:7000-7800"
    volumes:
     - ./frps.ini:/frps.ini
    restart: always
    command: -c frps.ini
  frp-client:
    image: hyperapp/frp
    volumes:
     - ./frpc.ini:/frpc.ini
    command: -c frpc.ini
    restart: always
    network_mode: "host"
    entrypoint:
     - /frpc
